# Fabric Deployment Configuration
# This file should be committed to your repository
# Secrets will be injected from GitHub Secrets during deployment

environments:
  dev:
    workspace_id: "6e6de13a-f2dc-4623-b3ac-431ec6d345f1"  # Replace with your dev workspace ID
    workspace_name: "ws-edp-dev"           # Replace with your dev workspace name
  prod:
    workspace_id: "17bf2e83-d6cc-4dcd-9e36-b355af66d6ad"      # Will be replaced by GitHub secret
    workspace_name: "__PROD_WORKSPACE_NAME__"  # Will be replaced by GitHub secret

# Simple string replacements (for notebook IDs, lakehouse IDs, etc.)
find_replace:
  # Raw Lakehouse replacements
  - find_value: "6e6de13a-f2dc-4623-b3ac-431ec6d345f1"  # Replace with actual dev lakehouse ID
    replace_value:
      dev: "6e6de13a-f2dc-4623-b3ac-431ec6d345f1"       # Same as find_value
      prod: "17bf2e83-d6cc-4dcd-9e36-b355af66d6ad"      # Will be replaced by GitHub secret
    item_type: "Notebook"
    file_path:
      - "01_bronze/**/*.py" # Adjust path to your notebook location
  
